export const CLASSIC_REVIEW_LABEL = "经典回顾 · 非本周新论文";

export const CLASSIC_PAPERS = Object.freeze([
  {
    paper_id: "classic-react-2023",
    dedupe_key: "openreview:WE_vluYUL-X",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    authors: [
      "Shunyu Yao",
      "Jeffrey Zhao",
      "Dian Yu",
      "Nan Du",
      "Izhak Shafran",
      "Karthik R. Narasimhan",
      "Yuan Cao",
    ],
    venue: "ICLR",
    paper_type: "conference-paper",
    published_at: "2023",
    issue_date: null,
    first_seen_at: null,
    doi: null,
    openreview_id: "WE_vluYUL-X",
    arxiv_id: "2210.03629",
    canonical_url: "https://openreview.net/forum?id=WE_vluYUL-X",
    official_url: "https://openreview.net/forum?id=WE_vluYUL-X",
    pdf_url: "https://openreview.net/pdf?id=WE_vluYUL-X",
    source_id: "conference-iclr",
    topic_matches: ["LLM Agent", "规划与工具使用"],
    abstract: "ReAct interleaves language-model reasoning traces with task actions so that plans can be updated using observations from external environments.",
    selection_summary: "经典的“推理—行动—观察”范式，用一篇论文建立工具调用型 Agent 的基本心智模型。",
    project_impact: "可作为 Pi Agent 步骤编排、工具调用记录和失败后继续执行的基础参照。",
    evidence_scope: "经典论文官方页面与全文",
    candidate_origin: "classic_review",
    is_new: false,
    display_label: CLASSIC_REVIEW_LABEL,
  },
  {
    paper_id: "classic-toolformer-2023",
    dedupe_key: "arxiv:2302.04761",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    authors: [
      "Timo Schick",
      "Jane Dwivedi-Yu",
      "Roberto Dessì",
      "Roberta Raileanu",
      "Maria Lomeli",
      "Eric Hambro",
      "Luke Zettlemoyer",
      "Nicola Cancedda",
      "Thomas Scialom",
    ],
    venue: "NeurIPS",
    paper_type: "conference-paper",
    published_at: "2023",
    issue_date: null,
    first_seen_at: null,
    doi: null,
    openreview_id: null,
    arxiv_id: "2302.04761",
    canonical_url: "https://proceedings.neurips.cc/paper/2023/hash/d842425e4bf79ba039352da0f658a906-Abstract-Conference.html",
    official_url: "https://proceedings.neurips.cc/paper/2023/hash/d842425e4bf79ba039352da0f658a906-Abstract-Conference.html",
    pdf_url: "https://proceedings.neurips.cc/paper_files/paper/2023/file/d842425e4bf79ba039352da0f658a906-Paper-Conference.pdf",
    source_id: "conference-neurips",
    topic_matches: ["规划与工具使用", "LLM Agent"],
    abstract: "Toolformer trains a language model to decide which APIs to call, when to call them, and how to incorporate the returned results.",
    selection_summary: "研究语言模型如何自监督学习调用 API，适合理解“何时用工具”这一核心 Agent 问题。",
    project_impact: "能帮助区分固定脚本动作、模型决策与工具调用三者的产品和运行时边界。",
    evidence_scope: "经典论文官方页面与全文",
    candidate_origin: "classic_review",
    is_new: false,
    display_label: CLASSIC_REVIEW_LABEL,
  },
  {
    paper_id: "classic-rag-2020",
    dedupe_key: "title:retrieval augmented generation for knowledge intensive nlp tasks:2020",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    authors: [
      "Patrick Lewis",
      "Ethan Perez",
      "Aleksandra Piktus",
      "Fabio Petroni",
      "Vladimir Karpukhin",
      "Naman Goyal",
      "Heinrich Küttler",
      "Mike Lewis",
      "Wen-tau Yih",
      "Tim Rocktäschel",
      "Sebastian Riedel",
      "Douwe Kiela",
    ],
    venue: "NeurIPS",
    paper_type: "conference-paper",
    published_at: "2020",
    issue_date: null,
    first_seen_at: null,
    doi: null,
    openreview_id: null,
    arxiv_id: "2005.11401",
    canonical_url: "https://proceedings.neurips.cc/paper/2020/hash/6b493230-Abstract.html",
    official_url: "https://proceedings.neurips.cc/paper/2020/hash/6b493230-Abstract.html",
    pdf_url: "https://proceedings.neurips.cc/paper_files/paper/2020/file/6b493230205f780e1bc26945df7481e5-Paper.pdf",
    source_id: "conference-neurips",
    topic_matches: ["RAG 与知识工作流", "记忆与上下文工程"],
    abstract: "RAG combines a pretrained generator with explicit non-parametric memory retrieved from a dense document index for knowledge-intensive generation.",
    selection_summary: "RAG 奠基论文，清楚区分参数记忆与可检索外部记忆，以及二者如何共同参与生成。",
    project_impact: "可用于设计项目资料检索、证据引用和只发送必要上下文的精简读取策略。",
    evidence_scope: "经典论文官方页面与全文",
    candidate_origin: "classic_review",
    is_new: false,
    display_label: CLASSIC_REVIEW_LABEL,
  },
  {
    paper_id: "classic-reflexion-2023",
    dedupe_key: "arxiv:2303.11366",
    title: "Reflexion: Language Agents with Verbal Reinforcement Learning",
    authors: [
      "Noah Shinn",
      "Federico Cassano",
      "Ashwin Gopinath",
      "Karthik Narasimhan",
      "Shunyu Yao",
    ],
    venue: "NeurIPS",
    paper_type: "conference-paper",
    published_at: "2023",
    issue_date: null,
    first_seen_at: null,
    doi: null,
    openreview_id: null,
    arxiv_id: "2303.11366",
    canonical_url: "https://proceedings.neurips.cc/paper_files/paper/2023/hash/1b44b878bb782e6954cd888628510e90-Abstract-Conference.html",
    official_url: "https://proceedings.neurips.cc/paper_files/paper/2023/hash/1b44b878bb782e6954cd888628510e90-Abstract-Conference.html",
    pdf_url: "https://proceedings.neurips.cc/paper_files/paper/2023/file/1b44b878bb782e6954cd888628510e90-Paper-Conference.pdf",
    source_id: "conference-neurips",
    topic_matches: ["LLM Agent", "记忆与上下文工程", "Agent 评估、可靠性与可追溯性"],
    abstract: "Reflexion lets language agents convert task feedback into verbal reflections stored in episodic memory and reused in later attempts.",
    selection_summary: "以语言反馈和情景记忆替代权重更新，是理解 Agent 如何从失败中继续改进的代表工作。",
    project_impact: "可直接启发 Run 反馈、阶段修正、提示词改进建议与可恢复执行的设计。",
    evidence_scope: "经典论文官方页面与全文",
    candidate_origin: "classic_review",
    is_new: false,
    display_label: CLASSIC_REVIEW_LABEL,
  },
  {
    paper_id: "classic-chain-of-thought-2022",
    dedupe_key: "openreview:_VjQlMeSB_J",
    title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
    authors: [
      "Jason Wei",
      "Xuezhi Wang",
      "Dale Schuurmans",
      "Maarten Bosma",
      "Brian Ichter",
      "Fei Xia",
      "Ed H. Chi",
      "Quoc V. Le",
      "Denny Zhou",
    ],
    venue: "NeurIPS",
    paper_type: "conference-paper",
    published_at: "2022",
    issue_date: null,
    first_seen_at: null,
    doi: null,
    openreview_id: "_VjQlMeSB_J",
    arxiv_id: "2201.11903",
    canonical_url: "https://proceedings.neurips.cc/paper_files/paper/2022/hash/9d5609613524ecf4f15af0f7b31abca4-Abstract.html",
    official_url: "https://proceedings.neurips.cc/paper_files/paper/2022/hash/9d5609613524ecf4f15af0f7b31abca4-Abstract.html",
    pdf_url: "https://proceedings.neurips.cc/paper_files/paper/2022/file/9d5609613524ecf4f15af0f7b31abca4-Paper-Conference.pdf",
    source_id: "conference-neurips",
    topic_matches: ["规划与工具使用", "Agent 评估、可靠性与可追溯性"],
    abstract: "Chain-of-thought prompting supplies intermediate reasoning exemplars and substantially improves sufficiently large language models on multi-step tasks.",
    selection_summary: "系统展示中间推理步骤如何改善复杂任务，是理解提示词结构与推理成本的基础论文。",
    project_impact: "能帮助精简各阶段提示词，并判断哪些中间过程值得保留、哪些只会增加 Token。",
    evidence_scope: "经典论文官方页面与全文",
    candidate_origin: "classic_review",
    is_new: false,
    display_label: CLASSIC_REVIEW_LABEL,
  },
]);
