export const WORKFLOW_ID = "journal-reading-v1-demo";

const sources = [
  ["ai", "Artificial Intelligence", "期刊", 8, "正常"],
  ["tpami", "IEEE TPAMI", "期刊", 6, "正常"],
  ["ijcv", "IJCV", "期刊", 4, "正常"],
  ["jmlr", "JMLR", "期刊", 3, "正常"],
  ["aaai", "AAAI", "会议", 7, "正常"],
  ["neurips", "NeurIPS", "会议", 11, "正常"],
  ["acl", "ACL Anthology", "会议", 13, "正常"],
  ["cvpr", "CVPR Open Access", "会议", 9, "正常"],
  ["iccv", "ICCV Open Access", "会议", 5, "正常"],
  ["icml", "ICML / PMLR", "会议", 12, "正常"],
  ["iclr", "ICLR / OpenReview", "会议", 8, "正常"],
].map(([id, name, type, discovered, health]) => ({
  id,
  name,
  type,
  discovered,
  health,
  cursor: "已保存至 2026-07-19 23:59（Asia/Shanghai）",
}));

const papers = [
  {
    id: "paper-context-ledger",
    title: "Context Ledgers for Verifiable Long-Horizon Agents",
    titleZh: "面向可核验长程智能体的上下文账本",
    authors: ["Lin Qiao", "Maya Chen", "R. Kapoor"],
    venue: "ACL 2026",
    publishedAt: "2026-07-16",
    firstSeenAt: "2026-07-18",
    discoveryType: "本周新发表",
    abstract: "论文把长期任务中的决定、证据与开放问题拆成可验证账本，并在每次工具调用前按需恢复相关状态。",
    relevance: "直接对应 Pi Agent 的“文件是真相、运行记录是索引”设计，可帮助约束项目状态的晋升规则。",
    recommendation: "直接推进项目",
    topicMatches: ["记忆与上下文工程", "Agent 可靠性与可追溯性"],
    heatSignals: ["公开讨论量位于本批次前 8%", "两份复现仓库在本周出现"],
    evidenceScope: "标题、摘要与热度信号；结论尚待全文核验",
    recommended: true,
    isDemo: true,
  },
  {
    id: "paper-human-gates",
    title: "Human Gates, Not Human Loops: Approval Design for Tool Agents",
    titleZh: "工具智能体中的人工门槛设计",
    authors: ["Sofia Martin", "Wei Luo"],
    venue: "ICML 2026",
    publishedAt: "2026-07-14",
    firstSeenAt: "2026-07-17",
    discoveryType: "本周新发表",
    abstract: "研究比较逐步确认、阶段确认和风险触发确认，认为确认点应围绕不可逆副作用而非每个推理步骤设置。",
    relevance: "能检验当前“逐项选择、一次批量确认”的交互是否兼顾控制感与工作流连续性。",
    recommendation: "拓展前沿视野",
    topicMatches: ["人机协作与人工确认", "规划与工具使用"],
    heatSignals: ["入选专题讨论", "引用在 5 天内出现 14 次"],
    evidenceScope: "标题、摘要与热度信号；结论尚待全文核验",
    recommended: true,
    isDemo: true,
  },
  {
    id: "paper-tracebench",
    title: "TraceBench: Evaluating Evidence-Carrying Agent Workflows",
    titleZh: "TraceBench：评估携带证据的智能体工作流",
    authors: ["Nora Singh", "T. Alvarez", "Hao Yu"],
    venue: "JMLR",
    publishedAt: "2026-06-28",
    firstSeenAt: "2026-07-15",
    discoveryType: "本周补发现",
    abstract: "提出同时检查最终答案、工具轨迹与证据覆盖率的评估集，并区分可恢复失败与静默错误。",
    relevance: "可作为未来端到端验收依据，但对当前前端闭环不是最紧迫输入。",
    recommendation: "候补",
    topicMatches: ["Agent 评估、可靠性与可追溯性"],
    heatSignals: ["下载量过去 7 天增长 31%"],
    evidenceScope: "摘要级证据",
    recommended: false,
    isDemo: true,
  },
  {
    id: "paper-budget-routing",
    title: "Budget-Aware Context Routing for Recurrent Research Tasks",
    titleZh: "周期研究任务中的预算感知上下文路由",
    authors: ["Emil Park", "Jiawen Sun"],
    venue: "NeurIPS 2026",
    publishedAt: "2026-07-11",
    firstSeenAt: "2026-07-16",
    discoveryType: "本周新发表",
    abstract: "用确定性筛选和分阶段语义路由减少重复上下文传输，并报告长周期任务中的 Token 降幅。",
    relevance: "与低 Token 目标相关，可在真实质量基线建立后用于第二轮降本。",
    recommendation: "候补",
    topicMatches: ["记忆与上下文工程", "RAG 与知识工作流"],
    heatSignals: ["收藏量位于本批次前 15%"],
    evidenceScope: "摘要级证据",
    recommended: false,
    isDemo: true,
  },
  {
    id: "paper-screen-evidence",
    title: "ScreenEvidence: Grounded Visual Traces for Computer-Use Agents",
    titleZh: "面向计算机使用智能体的视觉证据轨迹",
    authors: ["Akira Ito", "Lena Brooks"],
    venue: "CVPR 2026",
    publishedAt: "2026-07-10",
    firstSeenAt: "2026-07-17",
    discoveryType: "本周新发表",
    abstract: "把界面截图、操作区域与动作结果组织成可追溯视觉轨迹，用于发现计算机使用智能体的静默偏差。",
    relevance: "对未来界面操作型工作流有价值，但与首版期刊追踪闭环关系较弱。",
    recommendation: "候补",
    topicMatches: ["Agent 评估、可靠性与可追溯性"],
    heatSignals: ["项目页在本周更新了复现实验"],
    evidenceScope: "摘要级证据",
    recommended: false,
    isDemo: true,
  },
];

const guides = {
  "paper-context-ledger": {
    paperId: "paper-context-ledger",
    problem: "长程 Agent 在多轮任务后容易丢失决定来源，也难以区分模型草稿与人工确认的事实。",
    whyNow: "Pi Agent 正在确定项目状态、运行缓存和正式成果之间的边界，这篇论文正好提供可检验的状态模型。",
    intuition: "不要把整段历史对话当作记忆，而是维护带来源、状态和失效条件的上下文账本，按当前步骤检索。",
    evidence: "全文显示在三类长程任务上降低状态冲突；具体基线、样本量和失败案例仍需在精读阶段核验。",
    limitations: "目前只确认到论文正文与附录索引；跨项目迁移和用户修正后的冲突处理仍不清楚。",
    projectRelation: "可能把 project_state.md 的每条更新扩展为“结论 + 引用 + 确认时间 + 开放问题”，但 V1 不应因此引入复杂数据库。",
    questions: ["账本条目何时晋升为已确认事实？", "过期结论如何被替换而不破坏历史？", "这种结构是否真的比短摘要恢复更可靠？"],
    evidenceIds: ["ev-ledger-abstract", "ev-ledger-method"],
  },
  "paper-human-gates": {
    paperId: "paper-human-gates",
    problem: "工具 Agent 如果每一步都请求许可会打断工作；若只在最后确认，又可能隐藏不可逆操作。",
    whyNow: "首版正要实现 Zotero、Obsidian 与项目状态的一次批量确认，需要验证确认点应该放在哪里。",
    intuition: "根据副作用与可恢复性设置人工门槛：自由生成草稿，在真正写入前展示精确差异并统一批准。",
    evidence: "全文报告阶段门槛比逐步确认减少交互次数，同时保持风险发现率；量表和任务分布仍待核验。",
    limitations: "实验参与者数量有限，且没有覆盖本地知识工具的部分失败恢复。",
    projectRelation: "支持目前的内联批量确认，但也提示预览改变后必须使原批准失效。",
    questions: ["批量确认中哪些信息必须同时可见？", "部分失败是否会削弱用户对一次确认的理解？", "低风险写入能否在未来授权后自动化？"],
    evidenceIds: ["ev-gates-abstract", "ev-gates-results"],
  },
};

const readingStages = [
  {
    id: "research-question",
    label: "研究问题",
    prompt: "领域背景、缺口与贡献主张是什么？",
    content: {
      "paper-context-ledger": ["现有方法通常压缩整段历史，难以保留结论的证据状态。", "作者主张以细粒度账本取代无结构会话摘要。"],
      "paper-human-gates": ["现有许可设计在高打断率与低可见性之间摇摆。", "作者把确认定义为副作用发生前的可核验门槛。"],
    },
  },
  {
    id: "method",
    label: "方法机制",
    prompt: "信息如何流动，核心模块如何协作？",
    content: {
      "paper-context-ledger": ["抽取器生成候选条目，验证器标记来源与状态，路由器只取当前步骤所需条目。", "人工修正被记录为高优先级事件，而不是覆盖原始轨迹。"],
      "paper-human-gates": ["风险分类器先区分内部草稿、可恢复写入和不可逆操作。", "预览哈希把批准与具体内容绑定，内容变化会使批准失效。"],
    },
  },
  {
    id: "evidence",
    label: "实验证据",
    prompt: "数据、基线、结果与局限是否支撑主张？",
    content: {
      "paper-context-ledger": ["结果显示状态冲突下降，但任务规模与人工标注一致性仍需核验。", "失败案例集中在隐含决定和来源版本变化。"],
      "paper-human-gates": ["阶段门槛减少确认次数；对高风险错误的发现率与逐步确认接近。", "样本主要来自技术用户，外推到普通用户需谨慎。"],
    },
  },
  {
    id: "project-relation",
    label: "项目关系",
    prompt: "哪些思想可迁移，哪些项目决定应保持不变？",
    content: {
      "paper-context-ledger": ["保留 Markdown 事实源，只增加轻量的引用与确认字段。", "不因一篇论文就在 V1 引入向量数据库或自动记忆。"],
      "paper-human-gates": ["继续使用逐项勾选、一次提交，并在预览变化后要求重新确认。", "部分失败只重试失败项，已成功写入不回滚。"],
    },
  },
];

const evidence = [
  { id: "ev-scan", kind: "运行记录", label: "扫描清单", detail: "11/11 来源完成，86 条原始记录经标准化和去重后进入规则筛选。", scope: "脚本结果" },
  { id: "ev-ledger-abstract", paperId: "paper-context-ledger", kind: "摘要", label: "摘要第 1–3 段", detail: "支持研究问题与核心主张，不支持实验结论。", scope: "已核验" },
  { id: "ev-ledger-method", paperId: "paper-context-ledger", kind: "正文", label: "第 3 节", detail: "描述账本条目、验证状态与按需路由。", scope: "全文" },
  { id: "ev-gates-abstract", paperId: "paper-human-gates", kind: "摘要", label: "摘要与图 1", detail: "支持阶段门槛的设计动机。", scope: "已核验" },
  { id: "ev-gates-results", paperId: "paper-human-gates", kind: "正文", label: "第 5.2 节", detail: "比较逐步确认、阶段确认与风险触发确认。", scope: "全文" },
];

const proposals = [
  {
    id: "proposal-zotero",
    target: "zotero",
    targetLabel: "Zotero · Pi Agent 研读",
    operation: "为所选论文创建题录并附加 PDF/五分钟导读",
    paperIds: ["paper-context-ledger", "paper-human-gates"],
    preview: ["按 DOI/标题查重后创建题录", "附加所选论文的 PDF 与五分钟导读", "暂存 Obsidian 链接，待笔记写入后回填"],
    previewByPaperId: {
      "paper-context-ledger": ["查重并创建题录：Context Ledgers", "附加 PDF 与五分钟导读：Context Ledgers"],
      "paper-human-gates": ["查重并创建题录：Human Gates", "附加 PDF 与五分钟导读：Human Gates"],
    },
    isDemo: true,
  },
  {
    id: "proposal-obsidian",
    target: "obsidian",
    targetLabel: "Obsidian · 04_资料源/文章论文研读/Agent",
    operation: "为进入精读的论文创建可持续补充的主笔记",
    paperIds: ["paper-context-ledger", "paper-human-gates"],
    preview: ["一篇论文对应一篇主笔记", "写入已确认结论、用户问题与引用", "不覆盖已有同名文件"],
    previewByPaperId: {
      "paper-context-ledger": ["创建精读主笔记：Context Ledgers", "写入该论文的已确认结论、用户问题与引用"],
      "paper-human-gates": ["创建精读主笔记：Human Gates", "写入该论文的已确认结论、用户问题与引用"],
    },
    isDemo: true,
  },
  {
    id: "proposal-project-state",
    target: "project_state",
    targetLabel: "项目目录 · project_state.md",
    operation: "追加已确认的项目影响与开放问题",
    paperIds: ["paper-context-ledger", "paper-human-gates"],
    preview: ["决定：状态更新保留引用、确认时间与替代关系", "决定：写入批准必须绑定预览内容", "开放问题：V1 是否需要展示项目状态条目的失效原因？"],
    previewByPaperId: {
      "paper-context-ledger": ["决定：状态更新保留引用、确认时间与替代关系", "开放问题：V1 是否需要展示项目状态条目的失效原因？"],
      "paper-human-gates": ["决定：写入批准必须绑定预览内容"],
    },
    isDemo: true,
  },
];

export const workflowFixture = {
  fixtureLabel: "交互演示数据 · 不会扫描网络或写入真实 Zotero / Obsidian / 项目文件",
  workflowId: WORKFLOW_ID,
  workflowName: "期刊追踪与精读",
  project: {
    id: "pi-agent-product",
    name: "Pi Agent 产品设计",
    rootLabel: "/Users/…/pi Agent",
    statePath: "project_state.md",
    timezone: "Asia/Shanghai",
  },
  scanSummary: {
    window: "2026-07-13 — 2026-07-19",
    finishedAt: "2026-07-20 08:04",
    rawCount: 86,
    normalizedCount: 78,
    deduplicatedCount: 63,
    topicMatchedCount: 17,
    focusedCount: 5,
    tokenCostBeforeAiReview: 0,
  },
  sources,
  papers,
  guides,
  readingStages,
  evidence,
  projectState: {
    lastConfirmedAt: "2026-07-18 21:40",
    completed: ["确定项目是主体、工作流是推进方法", "确定文件是真相，数据库只做索引与运行记录"],
    decisions: ["首版只证明期刊追踪与精读闭环", "正式写入采用逐项选择、一次批准"],
    openQuestions: ["项目状态条目是否需要显式失效原因？"],
    nextAction: "评审本周候选，完成所选论文的导读与归档",
  },
  proposals,
};
