export const PROJECT_WORK_FIXTURE = {
  conversation: {
    id: "project-work-settings-mobile",
    kind: "project_work",
    title: "修复设置页移动端遮挡",
    rootLabel: "Pi Agent",
  },
  task: {
    id: "task-settings-mobile-footer",
    title: "修复设置页移动端底部按钮遮挡",
    summary: "让移动端设置页的底部操作按钮保持可见，同时不遮住最后一项设置内容。",
  },
  plan: [
    {
      id: "inspect",
      title: "检查设置页结构与移动端样式",
    },
    {
      id: "prepare-change",
      title: "准备最小布局修改",
    },
    {
      id: "verify",
      title: "核对变更并准备验证",
    },
  ],
  artifacts: [
    {
      id: "files",
      kind: "file",
      label: "文件",
    },
    {
      id: "changes",
      kind: "changes",
      label: "更改",
      badge: 2,
    },
    {
      id: "preview",
      kind: "preview",
      label: "预览",
    },
    {
      id: "run_result",
      kind: "run_result",
      label: "运行",
    },
  ],
  files: [
    {
      id: "settings-panel",
      path: "src/components/SettingsPanel.jsx",
      language: "jsx",
      focusLines: [3, 4, 5],
      content: [
        "export function SettingsPanel() {",
        "  return (",
        "    <section className=\"settings-panel\">",
        "      <div className=\"settings-panel__content\">…</div>",
        "      <footer className=\"settings-panel__footer\">…</footer>",
        "    </section>",
        "  );",
        "}",
      ],
    },
    {
      id: "app-styles",
      path: "src/styles.css",
      language: "css",
      focusLines: [8, 9, 10],
      content: [
        ".settings-panel {",
        "  display: grid;",
        "  grid-template-rows: auto 1fr auto;",
        "  min-height: 0;",
        "}",
        "",
        "@media (max-width: 640px) {",
        "  .settings-panel__content {",
        "    overflow-y: auto;",
        "  }",
        "}",
      ],
    },
  ],
  changeSet: {
    id: "change-settings-mobile-footer-v1",
    title: "设置页移动端底部操作区",
    baseHash: "sha256:settings-mobile-before-a91d",
    afterHash: "sha256:settings-mobile-after-c42e",
    files: [
      {
        id: "settings-panel",
        path: "src/components/SettingsPanel.jsx",
        operation: "update",
        additions: 2,
        deletions: 1,
        diff: [
          "@@ -2,6 +2,7 @@",
          "   return (",
          "-    <section className=\"settings-panel\">",
          "+    <section className=\"settings-panel settings-panel--mobile-safe\">",
          "+      <div className=\"settings-panel__scroll-region\">",
          "       <div className=\"settings-panel__content\">…</div>",
        ],
      },
      {
        id: "app-styles",
        path: "src/styles.css",
        operation: "update",
        additions: 7,
        deletions: 1,
        diff: [
          "@@ -7,5 +7,11 @@",
          " @media (max-width: 640px) {",
          "-  .settings-panel__content {",
          "+  .settings-panel__scroll-region {",
          "     overflow-y: auto;",
          "+    padding-bottom: calc(72px + env(safe-area-inset-bottom));",
          "+  }",
          "+",
          "+  .settings-panel__footer {",
          "+    position: sticky;",
          "+    bottom: 0;",
          "   }",
        ],
      },
    ],
  },
  preview: {
    title: "设置",
    desktopWidth: 960,
    mobileWidth: 390,
    mobileHeight: 844,
    footerLabel: "保存设置",
  },
  testRuns: {
    failed: {
      id: "settings-mobile-test-failed",
      command: "npm test -- SettingsPanel",
      status: "failed",
      exitCode: 1,
      durationMs: 842,
      summary: "移动端内容区仍少 16px 的安全底距",
      checks: [
        { id: "desktop-layout", label: "桌面布局保持不变", status: "passed" },
        { id: "mobile-footer", label: "底部按钮不遮挡内容", status: "failed" },
      ],
      logs: [
        "desktop viewport: passed",
        "mobile footer clearance: expected >= 16px, received 0px",
        "1 passed, 1 failed",
      ],
    },
    passed: {
      id: "settings-mobile-test-passed",
      command: "npm test -- SettingsPanel",
      status: "passed",
      exitCode: 0,
      durationMs: 791,
      summary: "桌面与移动端布局检查全部通过",
      checks: [
        { id: "desktop-layout", label: "桌面布局保持不变", status: "passed" },
        { id: "mobile-footer", label: "底部按钮不遮挡内容", status: "passed" },
      ],
      logs: [
        "desktop viewport: passed",
        "mobile footer clearance: 16px",
        "2 passed, 0 failed",
      ],
    },
  },
};
